### ISSUE TITLE
[FEATURE] Jellyfin/bazarr/filesystem support 

### ISSUE THREAD

**Issue by PovilasID** [McCloudS/subgen#3]
Having an option for Plex is cool, however, being more universal or supporting other media providers would be amazing.
There are couple suggestions you could do that.

1. Direct Jellyfin implementation. Jellyfin has an api https://api.jellyfin.org/ that should be to get what is needed by subgen to generate the files needed. (It might take a couple of calls though) (Jellyfin also has plugins for subs might be a good place to look)
2. bazarr. It is a tool that is used to download human made subs from multiple sites. It would be much better for users who need subs because human made ones would be higher quality (mostly) and people who do use subs a lot have it already. Bazarr works by polling it's providers so you would have to expose and API call to generate subs and then for it download them. It would also require writing a bazarr provider implementation.
3. Filesystem watching.  Adding an agent to watch file system to generate subs for all media files in a folder.

**Comment by McCloudS** [comment]
1. Totally reasonable.  If someone can give me some of the JSON responses, I can at least attempt it, but again, I won't be installing Jellyfin, so I won't be a great resource for integrating it.  
2. Agreed, but when I looked into integrating into Bazarr as a 'provider', it didn't seem worth the effort.  I might be overthinking it, but there wasn't obvious instructions on how to do it.  This is likely the best universal integration option.  
3. This is incredibly easy to do, but would need other rules in place.  Like checking if subtitles existed or if the file has internal subtitles.  Otherwise, you'll spend weeks generating subtitles.  I chose not to implement it at the time because the return on investment was pretty low.

**Comment by McCloudS** [comment]
Not planned at this time.  Might add a watchdog in the future, but there really isn't a reason for it if Plex or Tautulli is triggering on new media.  I understand the usecase for non-Plex, but I don't have the desire to spin up test environments that I will never use.

Open to any proposed merges.
