### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by xhzhu0628** [McCloudS/subgen#84]
Haha, it's still me. I deployed the service on Unraid and replaced the graphics card with a Tesla P4. 
The program successfully started running!

However, it seems that there is a memory leak issue in the program. When I add multiple tasks to the task queue at once, it consumes a large amount of memory and crashes the service. When I use "**--memory=5G**" in docker,  a single file can run (but I can observe a significant peak in system memory usage), but when I run multiple files, the log shows multiple "**Model was purged, need to re-create**" messages, followed by an error saying "**died with <Signals,SIGKILL.9>**" and stops.

![image](https://github.com/McCloudS/subgen/assets/66295967/cd0beea5-8e15-49ce-a11b-ea602b6a6d09)

**Comment by xhzhu0628** [comment]
And it seems that CONCURRENT_TRANSCRIPTIONS is not working. Although I set CONCURRENT_TRANSCRIPTIONS=1, in debug mode, I still see multiple progress bars in the log and it consumes more than the VRAM of a single video.

**Comment by McCloudS** [comment]
Yeah, CONCURRENT_TRANSCRIPTIONS doesn't really do anything right now.  I need to fix queuing and threading.  I've had better luck with WHISPER_THREADS.  

I've never had a leak or an OOM issues with the container on the P4.  The only time i've had it crash was trying to use a Large model with >60 min files.  I've easily had 100+ items in the 'queue' (use it loosely because it doesn't quite work) with 5+ items transcribing at the same time without any issues.  

Are you somehow memory constrained on your machine?  I'm running 32gb have have run the the exact container configuration you have for months without issue.

**Comment by xhzhu0628** [comment]
I'm currently running Unraid with 16GB of memory, but only 7GB is available.  Using a medium model with >120 min files.

**Comment by McCloudS** [comment]
I'm not sure.  This is what I see with about a dozen Mediums queued up in Bazarr.  

![image](https://github.com/McCloudS/subgen/assets/64094529/5a932aa9-a97f-490d-8cce-d133c4661ae3)
![image](https://github.com/McCloudS/subgen/assets/64094529/68276ffa-ddd5-4ef7-9290-321c087a07c1)

**Comment by xhzhu0628** [comment]
Finally, I found that there was a peak in RAM usage when loading large media files, even during GPU transcription. I solved this by enabling Swap Memory in Unraid.

By the way, I fix queuing by using threading.Thread() and create a PR
