### ISSUE TITLE
Still no cigar :(

### ISSUE THREAD

**Issue by sdspieg** [McCloudS/subgen#86]
I'm giving this another try. 

- I've set up the docker image, which seems to work ok 
- http://localhost:9000/ shows 
![image](https://github.com/McCloudS/subgen/assets/691472/36cff2bf-0c46-48d3-ba72-1968ea2c5f91) - which seems fine (I've set TRANSCRIBE_OR_TRANSLATE to 'translate')
- I've also set up the Plex webhook, and so when I play an item from my Plex, that does seem to trigger the hook - as visible in the following screenshot from my docker desktop (INFO:     172.20.0.1:50696 - "POST /plex HTTP/1.1" 200 OK) - 
![image](https://github.com/McCloudS/subgen/assets/691472/78052c9f-3004-4a34-bbbd-e4b34794ed66)

And yet I don't get any subtitles. Hence these questions:

- Is this supposed to work right away or does it take some time to 'kick in'?
- What should we put in the Playback settings on Plex under Subtitles? None? 
- Any other troubleshooting hints?

Thanks much for you efforts!

**Comment by McCloudS** [comment]
Is your plex token set and are you adding media to the library?  You have on play disabled, which is probably the log parts you’re seeing.  You only have onadded enabled, meaning media has to be added to your library to trigger a generation.

**Comment by McCloudS** [comment]
A sequence of events:

1. Plex sends to subgen that something was played or added to the library
2. Subgen receives it, sends something back to get the file path and determines based off of subgen settings (primarily based off of`PROCADDEDMEDIA` `PROCMEDIAONPLAY` `SKIPIFINTERNALSUBLANG`) to determine if it needs to generate subtitles
3. Subgen runs, and assuming you have the same docker paths mounted between Plex/Subgen, it will place a subtitle next to the file loosely named `mediafile.subgen.{whisper_model}.{namesublang}.srt`
4. You select the external subtitle under playback settings.

**Comment by sdspieg** [comment]
> Is your plex token set

Yes. 

> are you adding media to the library

No. I'm just playing existing media. Does it not work on those? 

> You only have onadded enabled, meaning media has to be added to your library to trigger a generation.

Ok - I'll look into that

**Comment by McCloudS** [comment]
Yup, you'll want both of those true.  So it will process subtitles for any new media added and anything that is played.  The issue with the played is you will be waiting X minutes (for the transcription to finish) before it's ready.  Which is fine my use-case because my GPU cranks them out in a couple minutes, so we just turn the subtitle on a couple minutes into a show if we need to.  

Sorry, by Docker paths, I meant your volumes.  So my personal setup on Plex AND Subgen have the following mounted as volumes: 
![image](https://github.com/McCloudS/subgen/assets/64094529/d78c72c9-5663-4792-b11f-1fa3060708ad)

I have both `PROCADDEDMEDIA` and `PROCMEDIAONPLAY` set to true and `SKIPIFINTERNALSUBLANG` to eng.   `SKIPIFINTERNALSUBLANG` is there if you want it, so I don't waste time generating subtitles that already have internal english ones (or whatever you set) in the file.  

I think you're pretty close to a working solution.

**Comment by sdspieg** [comment]
> I think you're pretty close to a working solution.
Sounds great! (Theoretically!)

> my GPU cranks them out in a couple minutes, so we just turn the subtitle on a couple minutes into a show if we need to.
So I have an RTX-4090, AND I have CUDA installed etc. So it seems to me this SHOULD be working just fine! (it just doesn't - yet..)

> So my personal setup on Plex AND Subgen have the following mounted as volumes:
Here's what I have in my 'docker-compose.yml' for this - these are all my (wsl) folders that have content. Is there anything wrong with this part?
```
    volumes:
      - "/mnt/c/Plex/subgen/subgen:/subgen"
      - "/mnt/c/Plex/whisper:/whisper"
      - "/mnt/c/Plex/Movies:/media/Movies"
      - "/mnt/c/Plex/Russian movies:/media/Russian movies"
      - "/mnt/h/Plex/Movies:/media/Movies2"
      - "/mnt/h/Plex/TVShows:/media/TVShows"
      - "/mnt/h/Plex/Russian movies:/media/Russian movies2"
      - "/mnt/i/Plex/Audiobooks:/media/Audiobooks"
      - "/mnt/i/Plex/Downloads:/media/Downloads"
      - "/mnt/i/Plex/Library:/media/Library"
      - "/mnt/i/Plex/Movies:/media/Movies3"
      - "/mnt/i/Plex/temp:/media/temp"
      - "/mnt/i/Plex/TVShows:/media/TVShows2"
``` 
I also have set SKIPIFINTERNALSUBLANG to eng... Can't wait to get this fully working!!! And thanks for your patient support...

**Comment by McCloudS** [comment]
If those volumes are shared across the containers, that should be correct.
